name: Publish In Docker Hub
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Docker build
        run: docker build ./clean-architecture-template/CleanArchitectureTemplate.Api -t darianbenito/clean-architecture-template/CleanArchitectureTemplate.Api
      - name: Push to Docker Hub
        uses: docker push darianbenito/clean-architecture-template/CleanArchitectureTemplate.Api
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: darianbenito/debian
          tag_with_ref: true
