name: Publish Docker image (CI)
on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 * * * *"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: temp
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: darianbenito/temp
          tag_with_ref: true
