name: Publish Docker image (CI)
on:
  push:
    branches:
      - master
  #### schedule:
  ####  - cron: "0 * * * *"
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: build the root Dockerfile, tag the image as darianbenito/clean-architecture-template-repository:latest, log in to Docker Hub using GitHub secrets, and push the image to the Docker Hub repository darianbenito/clean-architecture-template-repository
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          repository: darianbenito/clean-architecture-template-repository
          tags: latest
